AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your Docker-based function.

Resources:
  Parameters:
    ImageUri:
      Type: String
      Default: 559050235894.dkr.ecr.us-east-1.amazonaws.com/graalvm-demo:latest
      Description: The URI of the Docker image to use for the Lambda function.
  graalvmDemoResource:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: hop-be-function-native-image
      PackageType: Image
      MemorySize: 512
      Timeout: 90
      Architectures:
        - x86_64
      ImageUri: !Ref ImageUri
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:us-east-1:559050235894:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:us-east-1:559050235894:log-group:/aws/lambda/graalvm-demo:*
      SnapStart:
        ApplyOn: None
