spring:
  datasource:
    url: jdbc:mysql://gateway01.eu-central-1.prod.aws.tidbcloud.com:4000/graalvm_demo
    username: 44L5dMzv8pZN8Xu.root
    password: U2vAs5GJNoZLLqJN
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
