name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Verify Java installation
        run: |
          echo $JAVA_HOME
          java -version
          echo ${{steps.setup-java.outputs.java-home}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Prepare environment variables
        run: |
          echo "REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "REPOSITORY=graalvm-demo" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Set FULL_IMAGE_NAME
        run: echo "FULL_IMAGE_NAME=${{ env.REGISTRY }}/${{env.REPOSITORY}}:${{env.IMAGE_TAG}}" >> $GITHUB_ENV

      - name: Build native image
        run: docker build --progress=plain --platform linux/amd64 -t ${{ env.FULL_IMAGE_NAME }} .

      - name: Push docker image to Amazon ECR Public
        run: docker push ${{ env.FULL_IMAGE_NAME }}

      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v1

      - name: Package SAM application
        run: |
          sam package \
            --template-file template.yml \
            --output-template-file packaged.yml \
            --image-repository 559050235894.dkr.ecr.us-east-1.amazonaws.com/graalvm-demo \

      - name: Deploy SAM application
        run: |
          sam deploy \
            --template-file packaged.yml \
            --stack-name graalvm-lambda-stack \
            --capabilities CAPABILITY_IAM \
            --region us-east-1 \
            --image-repository 559050235894.dkr.ecr.us-east-1.amazonaws.com/graalvm-demo \
            --parameter-overrides ImageUri=${{ env.FULL_IMAGE_NAME }} \
            --force-upload
